### ISSUE TITLE
Usage with Panel CSS config option

### ISSUE THREAD

**Issue by tobimori** [lukaskleinschmidt/kirby-laravel-vite#1]

**Comment by lukaskleinschmidt** [comment]
It is possible. But right now you need to use the `vite()` helper in the [`ready`](https://getkirby.com/docs/reference/system/options/ready) callback has the `Vite` class requires a kirby instance to work properly. In addition to that kirby only allows relative asset paths here and skips URLs. So right now you need to use a little workaround to make it work.

This example does work but only once the assets are actually build. So no hot reloading for now:
```php
<?php

return [
    'ready' => fn () => [
        'panel' => [
            'css' => parse_url(vite()->asset('assets/css/panel.css'), PHP_URL_PATH),
        ],
    ]
];
```

You also have to specify the panel styles in your vite config:
```js
export default defineConfig({
  plugins: [
    laravel([
      'assets/css/app.css',
      'assets/css/panel.css',
      'assets/js/app.js',
  ],
});
```

That's how you can use it right now.

## Good news :)
I actually have a solution to get everything working with hot reloading as well. Still just as a concept. But I might get a release out for this later today. Just need to tidy things up so everything is working as expected.

You would then be able to use it like this in your config:
```php
<?php

return [
    'ready' => fn () => [
        'panel' => [
            'css' => vite('assets/css/panel.css'),
        ],
    ]
];
```

**Comment by lukaskleinschmidt** [comment]
Should work fine now with the [latest release](https://github.com/lukaskleinschmidt/kirby-laravel-vite/releases/tag/1.1.0)
