### ISSUE TITLE
Panel update check not working

### ISSUE THREAD

**Issue by tobimori** [lukaskleinschmidt/kirby-laravel-vite#2]
<img width="342" alt="CleanShot 2023-05-30 at 19 36 44@2x" src="https://github.com/lukaskleinschmidt/kirby-laravel-vite/assets/29142128/87e833af-a523-4575-9aeb-cea7867ac202">

**Comment by lukaskleinschmidt** [comment]
Probably has something to do with [this line](https://github.com/lukaskleinschmidt/kirby-laravel-vite/blob/main/composer.json#L22). I can see the same problem for example with https://github.com/fabianmichael/kirby-meta (where I picked up that config option) in the panel.

I will open an issue in the Kirby repo as I think this needs to be resolved there.

![grafik](https://github.com/lukaskleinschmidt/kirby-laravel-vite/assets/10027897/de4aa224-b241-420d-9c5b-3d20ebc65a05)

**Comment by lukaskleinschmidt** [comment]
Nevermind. Figured it out 😅
